//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNet.T4Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermissMenu
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public string Icon { get; set; }
        public int Sort { get; set; }
        public System.DateTime AddDate { get; set; }
        public string ControllerNameCode { get; set; }
        public string ActionNameCode { get; set; }
        public Nullable<bool> HaveChild { get; set; }
        public int MenuLevel { get; set; }
    }
}
