//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNet.T4Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermissUserDetails
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public string RealName { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<System.DateTime> Birth { get; set; }
        public string IdentityCardNumber { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string Description { get; set; }
    }
}
