//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNet.T4Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermissUserLogin
    {
        public System.Guid Id { get; set; }
        public string UserName { get; set; }
        public bool IsAble { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public string UserEmail { get; set; }
        public System.DateTime ApplyDate { get; set; }
        public int DeleteFlag { get; set; }
        public string ShortDescription { get; set; }
        public string LoginId { get; set; }
        public string LoginPwd { get; set; }
        public string PhotoPath { get; set; }
    }
}
