//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNet.T4Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class T4ModelConn : DbContext
    {
        public T4ModelConn()
            : base("name=T4ModelConn")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PermissButton> PermissButton { get; set; }
        public virtual DbSet<PermissDepartment> PermissDepartment { get; set; }
        public virtual DbSet<PermissMenu> PermissMenu { get; set; }
        public virtual DbSet<PermissRefMenuButton> PermissRefMenuButton { get; set; }
        public virtual DbSet<PermissRefRoleMenuButton> PermissRefRoleMenuButton { get; set; }
        public virtual DbSet<PermissRefUserDepartment> PermissRefUserDepartment { get; set; }
        public virtual DbSet<PermissRefUserMenuButton> PermissRefUserMenuButton { get; set; }
        public virtual DbSet<PermissRefUserRole> PermissRefUserRole { get; set; }
        public virtual DbSet<PermissRole> PermissRole { get; set; }
        public virtual DbSet<PermissUserDetails> PermissUserDetails { get; set; }
        public virtual DbSet<PermissUserLogin> PermissUserLogin { get; set; }
        public virtual DbSet<StateBug> StateBug { get; set; }
        public virtual DbSet<StateLoginLog> StateLoginLog { get; set; }
        public virtual DbSet<StateOperateLog> StateOperateLog { get; set; }
    }
}
